controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true
    
    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:

    publish_rate: 30.0
    base_frame_id: base_link

    left_wheel_names: ["left_front_joint","left_rear_joint"]
    right_wheel_names: ["right_front_joint","right_rear_joint"]
    wheel_separation: 0.5 #1.4
    wheel_radius: 0.1 #0.3075

    enable_odom_tf: false
    use_stamped_vel: false
    
#joint_state_broadcaster:
#  ros__parameters:
#    publish_rate: 100.0
#    use_sim_time: true
